version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    depends_on:
      - db
    networks:
      - db_network
    restart: always

  db:
    image: postgres:latest
    ports:
      - "5433:5433"
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./db-data:/var/lib/postgresql/data
      #- ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db_network
    restart: always

networks:
  db_network:
    driver: bridge