version: "3"
services:
  server:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    depends_on:
      db:
        condition: service_healthy
#    networks:
#      - db_network
    restart: always
    working_dir: /app
    network_mode: bridge

  db:
    image: postgres:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - ./db-data:/var/lib/postgresql/data
      #- ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    network_mode: bridge
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s

#networks:
#  db_network:
#    driver: bridge