version: "3"
services:
  server:
    build: .
    container_name: server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - db
#      db:
#        condition: service_healthy
#    networks:
#      - db_network
    restart: always
    working_dir: /app
    network_mode: bridge
    volumes:
      - ./photos:/photos

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:${DB_PORT}"
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
      #- ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    network_mode: bridge
    restart: always
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U $DB_USER" ]
#      interval: 10s

#networks:
#  db_network:
#    driver: bridge